### ISSUE TITLE
Улучшения работы

### ISSUE THREAD

**Issue by gNikro** [mayakwd/as3-vanilla-ice#2]
https://github.com/mayakwd/as3-vanilla-ice/blob/master/src/org/osflash/vanilla/reflection/util/ReflectionUtil.as#L9

Мозно заменить на будет гораздо быстрее работать чем getQualifiedClassName

```
object.constructor.toString().substr(7, 6) == "Vector"
```

https://github.com/mayakwd/as3-vanilla-ice/blob/master/src/org/osflash/vanilla/reflection/util/ReflectionUtil.as#L25

is Number || is String || is Int будет же работать намного быстрее 

https://github.com/mayakwd/as3-vanilla-ice/blob/master/src/org/osflash/vanilla/reflection/util/ReflectionUtil.as#L16

```
return object.constructor as Class
```

https://github.com/mayakwd/as3-vanilla-ice/blob/master/src/org/osflash/vanilla/reflection/util/ReflectionUtil.as#L38

Разве не необходима проверка на принимаемые параметры классом?

```
var constructorInfo:XMLList = typeDescription.constructor.parameter;
```

https://github.com/mayakwd/as3-vanilla-ice/blob/master/src/org/osflash/vanilla/reflection/map/impl/BaseInjectionMapFactory.as

А тут бы дескрайб джсон делать и кешировать его чтобы дескрайб каждый раз не делать

**Comment by mayakwd** [comment]
> https://github.com/mayakwd/as3-vanilla-ice/blob/master/src/org/osflash/vanilla/reflection/util/ReflectionUtil.as#L9
> Мозно заменить на будет гораздо быстрее работать чем getQualifiedClassName

```
object.constructor.toString().substr(7, 6) == "Vector"
```

Принимает значения: строка\объект\класс, для всех трёх кейсов текущая реализация работает должным образом. При предложенной реализации будет работать только для инстансов, для любого из классов вектора, например Vector.<String> возвратит [class Class], для строк [class String] соответственно.

> https://github.com/mayakwd/as3-vanilla-ice/blob/master/src/org/osflash/vanilla/reflection/util/ReflectionUtil.as#L25
> is Number || is String || is Int будет же работать намного быстрее

Разницы в скорости не будет никакой, пока не будет парситься за один тик несколько десятков тысяч записей, да и там разница будет незначительна.

Кроме этого текущая запись выглядит несколько приятнее, чем:

```
object is int || object is uint || object is String || object is Boolean || object is Number || object is Date || object is Array
```

> https://github.com/mayakwd/as3-vanilla-ice/blob/master/src/org/osflash/vanilla/reflection/util/ReflectionUtil.as#L16

```
return object.constructor as Class
```

Как и в первом случае value может быть строкой\объектом\классом, поэтому данное решение не подходит.

> https://github.com/mayakwd/as3-vanilla-ice/blob/master/src/org/osflash/vanilla/reflection/util/ReflectionUtil.as#L38
> Разве не необходима проверка на принимаемые параметры классом?

Зачем, чтобы выкинуть исключение в случае несоответствия количества аргументов и промапаных полей? Пользователь должен самостоятельно озаботиться параметрами принимаемыми конструктором класса https://github.com/mayakwd/as3-vanilla-ice#mapping-to-constructor-arguments

Помимо этого describeType не возвращает имен аргументов, а лишь типы и их опциональность. Гадание на кофейной гуще.

> https://github.com/mayakwd/as3-vanilla-ice/blob/master/src/org/osflash/vanilla/reflection/map/impl/BaseInjectionMapFactory.as
> А тут бы дескрайб джсон делать и кешировать его чтобы дескрайб каждый раз не делать

Безусловно describeTypeJSON быстрее, чем describeType, но метод является недокументированным, и нет гарантии, что он не будет убран в будущих версиях. 

Кеширование производится на слое выше. Кешируется на жирный и бесполезный после парсинга XML, а карта инжектов, созданная любым из IInjectionMapFactory.

**Comment by gNikro** [comment]
> Принимает значения: строка\объект\класс, для всех трёх кейсов текущая реализация работает должным образом. При предложенной реализации будет работать только для инстансов, для любого из классов вектора, например Vector. возвратит [class Class], для строк [class String] соответственно.

Так нужно и сделать корректную обработку и для строки и для класса и для объекта если такая необходимость есть. И обрабатывать это корректно не из как обжект а корректно
extractTypeNameAsString(...)...

Это ведь в разы наглядней да и скорость обработки быстрее. Десятки тысяч объектов могут вполне парситься. Или даже сотни постоянно

> Разницы в скорости не будет никакой, пока не будет парситься за один тик несколько десятков тысяч записей, да и там разница будет незначительна.

Разница в скорости будет особенно с наложением на остальные узкие места
Допустим возьму я эту либу и буду юзать в ммо проекте. На каждый кадр я буду высылать на 100 человек как минмиум 100 объектов содержащих поинты, намберы, инты, векторы.

А запись вида >object is int || object is uint || object is String || object is Boolean || object is Number || object is Date || object is Array

Выглядит лучше хотя бы тем что она соотвествует регламенту AS3

> Как и в первом случае value может быть строкой\объектом\классом, поэтому данное решение не подходит

Как и в первом случае следуюет привести программу к логичному поведению getClassFromStirng getClassFromObject и тд
Да даже в этом методе если он один сделать всего лишь проверку is String is Object

Меньше дискрайбтайпов, меньше гет дефенишенов в разы меньше алокейтов памяти происходит и работа происходит намного быстрее

> Зачем, чтобы выкинуть исключение в случае несоответствия количества аргументов и промапаных полей? Пользователь должен самостоятельно озаботиться параметрами принимаемыми конструктором класса https://github.com/mayakwd/as3-vanilla-ice#mapping-to-constructor-arguments

Почему бы это не перехватить самостоятельно и вывести корректную ошибку. В каком аргументе ошибка. В количистве ли аргументов ошибка разве это плохо? Думаю нет

> Помимо этого describeType не возвращает имен аргументов, а лишь типы и их опциональность. Гадание на кофейной гуще.

Так и что? Зато он возвращает индексы аругментов и типы. Индекс аругмента это гадание на кофейной гуще? Похоже мы в разных мирах живем. Может индекс массива тоже не дает понятие о каком элементе массива идет речь?

> Безусловно describeTypeJSON быстрее, чем describeType, но метод является недокументированным, и нет гарантии, что он не будет убран в будущих версиях.

Есть 100%ая гарантия что его никогда никуда не уберут. Мало того что он существует уже 100 лет так и АВМ+ задокументирвоан и презентирован адобом
В пример можно привести spring as3, parley, as3commons, the miner и прочие либы которые без каких либо опасений используют авм+. Не думаю что эта либа в 20 строчек кода пострадает даже если такое и случится

**Comment by mayakwd** [comment]
> Так нужно и сделать корректную обработку и для строки и для класса и для объекта если такая необходимость есть. И обрабатывать это корректно не из как обжект а корректно
> extractTypeNameAsString(...)...

Я подумаю над этим предложением.

> Разница в скорости будет особенно с наложением на остальные узкие места
> Допустим возьму я эту либу и буду юзать в ммо проекте. На каждый кадр я буду высылать на 100 человек как минмиум 100 объектов содержащих поинты, намберы, инты, векторы.

Крайне сомнительная ситуация, скорее мысленный эксперимент. При разработке ММО, никто не будет проводить двойную десериализацию, хотя бы потому, что будет использоваться бинарный формат сообщений, с прямым парсингом в типизированный объект, а никак не десериализация в сырой объект, а потом из него в типизированную структуру.

> Выглядит лучше хотя бы тем что она соотвествует регламенту AS3

Регламенту AS3? Но мысль хороша, внесу изменения.

> Как и в первом случае следуюет привести программу к логичному поведению getClassFromStirng getClassFromObject и тд
> Да даже в этом методе если он один сделать всего лишь проверку is String is Object

Я подумаю над этим предложением. 

> Так и что? Зато он возвращает индексы аругментов и типы. Индекс аругмента это гадание на кофейной гуще? Похоже мы в разных мирах живем. Может индекс массива тоже не дает понятие о каком элементе массива идет речь?

Что за нападки? Конструктивный ответ будет вполне самодостаточен и без "похоже мы живем в разных мирах". Подумаю над этим предложением.

**Comment by gNikro** [comment]
> Крайне сомнительная ситуация, скорее мысленный эксперимент. При разработке ММО, никто не будет проводить двойную десериализацию, хотя бы потому, что будет использоваться бинарный формат сообщений, с прямым парсингом в типизированный объект, а никак не десериализация в сырой объект, а потом из него в типизированную структуру.

В смысле? Конечно будет десериализация в сырой объект в набор байтов. Любой объект это последовательность интов, намберов ну и чего угодно. Должно быть правило как его считать и как записать. В пример тот же потом или графит или даже амф. 

Бинарные данные тоже дожлны иметь структуру и чем мы меньше потратим оверхеда на эту стурктуру тем лучше. Например я сейчас десирализцую в последовательные наборы примитивов все объекты допустим {int, point, string}  я десерализую в такой же поток байт. Заголовок с размером пакета и далее int int int utf header utf bytes и считаю его точно так же.

Если брать графит или амф то амф дает оверхед дописывая где нужно флаги типов и при считывании объектов сириализует его имея уже готовую структуру для чтения после вызова registerClassAliace по большему счету там примерно та же реализация что и тут с жсоном

**Comment by mayakwd** [comment]
В смысле, что эта библиотека не пригодится для MMO :-) Так как для той же цели будет использована более подходящая технология для работы со структурированными сжатыми данными.

**Comment by gNikro** [comment]
На этапе отладки и проектирвоаняи вполне. Жсон то читаемый глазами а байтаррей не особо
